services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"
    
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    platform: linux/x86_64
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////tmp/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - mongodb

volumes:
  mongo-data:
